### ISSUE TITLE
Missing git repository for libkkc-data

### ISSUE THREAD

**Issue by Arfrever** [ueno/libkkc#27]
It seems that some years ago https://bitbucket.org/libkkc/libkkc-data existed.
One libkkc-data tarball is available on https://github.com/ueno/libkkc/releases, but no git repository for libkkc-data can be found.

**Comment by ueno** [comment]
That's because the scripts to generate the data are in the main repository: https://github.com/ueno/libkkc/tree/master/data/templates/libkkc-data

**Comment by tinywrkb** [comment]
It's not clear where the language model `data.arpa` comes from. It would be nice to have it in a git repo, here or a separate one.
