### ISSUE TITLE
"dzu" not accepted in default rom-kana map for づ

### ISSUE THREAD

**Issue by xorgy** [ueno/libkkc#33]
I feel that since there is no conflict, it shouldn't be a problem to accept both `"du"` and `"dzu"` for づ. With the default `rom-kana` mapping, when you type `"dzu"`  you get ず, which is frustrating. I get that experienced native Japanese speakers would know to use `"du"` instead, but I had to visit the json to figure this one out.

**Comment by ueno** [comment]
I wonder how common this translation is; have you checked other IMs, such as Windows, macOS, etc?

**Comment by xorgy** [comment]
I'm not sure about input methods, but most romanizations use dzu for づ

**Comment by pprkut** [comment]
I looked a bit around and found these references:

https://hinative.com/ja/questions/78311
https://community.wanikani.com/t/how-to-type-%E3%81%A5/33891/9
https://nl.qaz.wiki/wiki/Tsu_(kana) (in dutch)

The consensus seems to be that `dzu` is valid, though uncommon, and most IMEs don't seem to know about it (but I didn't actually check that last part myself, just based on comments in those forums)

**Comment by ueno** [comment]
Thanks for checking. So I guess it would be no harm to add it in the default rule (which is derived from [ddskk](https://github.com/skk-dev/ddskk/blob/master/skk-vars.el#L685)). I'm going to merge #34 shortly.

**Comment by xorgy** [comment]
Thank you, I appreciate it. :+ )
